spring.application.name=LATRA
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LATRA;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ?ã s?a thành none: B?t Hibernate tôn tr?ng c?u trúc SQL Server c?a b?n, c?m t? s?a b?y b?
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
# Gi? nguyên ?? ép m?i chu?i String trong Java thành NVARCHAR (H? tr? ti?ng Vi?t)
